[package]
name = "pokemon-data-scraper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustemon = "3.4.0" 
serde_json = "1.0.116"
sqlite = "0.35.0"
tokio = { version = "1.0", features = ["full"] }
